<div id="login-form" class=" widget ui-widget ui-corner-all border-box">
	<h2 class="ui-widget-header ui-corner-all">Dashboard Login</h2>
	<div class="ui-widget-content login-form-content">
		<?php if(isset($errors)) { ?>
			<?php foreach($errors as $error) { ?>
				<div class="error"><?=$error?></div>
			<?php } ?>
		<?php } ?>
		<form method="post">
			<div class="form-input">
				<label for="username">Username</label>
				<input type="text" name="username" placeholder="Username" />
			</div>
			<div class="form-input">
				<label for="password">Password</label>
				<input type="password" name="password" placeholder="Password" />
			</div>
			<input type="submit" value="Login" />
		</form>
	</div>
</div>